### PR TITLE
Remove `MANGOHUD_CONFIG` environment variable that prevents using a `MangoHud.conf` file

### LINKED ISSUE #206: Mangohud.conf where is it?
Hello moderator,

So today i was installed gamer os which is pretty awsome, and i did some test of my games with mangohud which is you need to press F3 to toggle it. However, i noticed that there is only few basic info, such as fps, cpu usage and gpu usage. So i want to adding more option like ram usage, ect but i cant find it anywhere. I've use another distro to access frfrz_root partition and search for mangohud.conf but i cant find it.

Could you tell me where is locate?

### PR DESCRIPTION
**Pull request by Samsagax**
This should fix https://github.com/gamer-os/gamer-os/issues/206

### CODE REVIEW

**Comment by alkazar** [comment]
I can't merge this because it will break existing functionality.

1) it will cause mangohud to always appear (I only want it to appear when the user toggles it on from Steam Buddy)
2) it will cause the toggling to no longer work from Steam Buddy because the key combo would be changed

What needs to be done is:
a) move the `no_display` option to the mangohud configuration file instead
b) the key combination should be changed in Steam Buddy to use the new default (Shift_R+F12). The default key combo used to be F12 which conflicted with the Steam screenshot capture shortcut.

**Comment by Samsagax** [comment]
> I can't merge this because it will break existing functionality.
> 
>     1. it will cause mangohud to always appear (I only want it to appear when the user toggles it on from Steam Buddy)
> 
>     2. it will cause the toggling to no longer work from Steam Buddy because the key combo would be changed
> 
> 
> What needs to be done is move these default values to the mangohud configuration file instead.

Then this PR should be added in addition to those changes inside `gamer-os` repository. Maybe write the MangoHud.conf file and copy it to `/etc/MangoHud/MangoHud.conf` and set `MANGOHUD_CONFIG` environment variable pointing to it.

**Comment by alkazar** [comment]
> Then this PR should be added in addition to those changes inside `gamer-os` repository. Maybe write the MangoHud.conf file and copy it to `/etc/MangoHud/MangoHud.conf` and set `MANGOHUD_CONFIG` environment variable pointing to it.

I think that will still have the same problem that people will not be able to override the configuration. I think we should create a default mangohud config in the user's home directory (if it doesn't exist). I was planning on doing this work soon.

**Comment by Samsagax** [comment]
> I think that will still have the same problem that people will not be able to override the configuration. I think we should create a default mangohud config in the user's home directory (if it doesn't exist). I was planning on doing this work soon.

I see... Maybe make steam-buddy create that file if it doesn't exist with a default one?

**Comment by Samsagax** [comment]
This can be merged after https://github.com/gamer-os/steam-buddy/pull/143

**Pull request merged**
