### PR TITLE
Show FPS during games

### PR DESCRIPTION
**Pull request by sharkwouter**
This pull request will enable SteamOS Compositor Plus to show the FPS while playing a game. It can be activated with F10 and it only works in games, not in Steam. Let me know what you think of it.

### CODE REVIEW

**Review by protheory8 — APPROVED** [review]

**Comment by alkazar** [comment]
Looks good, just needs some testing.

**Comment by sharkwouter** [comment]
I will probably be able to test it on GamerOS this weekend. So far it has been tested on Arch.

I was thinking I could probably ~~improve the interaction with the debug mode (currently you can have both enabled, in which case it will probably show the fps twice) and~~ add a command line option which enables this feature by default.

Edit: the fps will not be displayed twice, the method for displaying the FPS will not be called if the debug mode is enabled. I forgot I had implemented that. I still think it has value to add a command line option to enable displaying the FPS in games. I will get to that this weekend and I will add it to this PR.

**Comment by sharkwouter** [comment]
I did some testing and added a command line option.

The bad news is that this change makes games unable to use whichever key was set as a hotkey. I'm not quite sure how to fix this yet.

**Comment by alkazar** [comment]
I guess that is kind of a blocker. At least for enabling this by default.

**Pull request closed without merging**
